[build]
    command = "npm run build"
    publish = "build"

[[redirects]]
    from = "/api/*"
    to = "https://newsapi.org/v2/:splat"
    status = 200
    force = true
    headers = {Access-Control-Allow-Origin = "*"}